spring:
  application:
    name: products
  profiles:
    active: default
  config:
    import: "optional:configserver:http://localhost:8070/"
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test_db
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8071/eureka/
